# Generated by Django 5.0.2 on 2024-04-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='price',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
